export const WEBSITE_BASE_URL = 'https://new-grocery.vercel.app/'
export const PRODUCTS_BASEURL = 'https://rabbitmart-products.vercel.app/products'
export const ORDERS_BASEURL = 'https://rabbitmart-orders.vercel.app/orders'
export const SHIPPING_BASEURL = 'https://rabbitmart-shipping.vercel.app/shipping'
export const NOTIFICATIONS_BASEURL = 'https://rabbitmart-notifications.vercel.app/notifications'
export const PAYMENTS_BASEURL = 'https://new-grocery-payments.vercel.app/'
export const USER_BASEURL = 'https://rabbitmart-users.vercel.app/me'